### ISSUE TITLE
fallback to firebase realtime in network conditions where  webrtc p2p fails

### ISSUE THREAD

**Issue by no-1ne** [podraven/y-fire#9]
Helllo folks, 
currently as mentioned in the readme, 

1. Utilizes a peer-to-peer network to exchange real-time data and awareness.
2. Utilizes Firestore as persistent storage and syncs with Firestore periodically to maintain persistent data state.

Sometimes in TURN usecases NAT punching failing etc, which as per internet can be 10% of traffic,  we either need a SFU or TURN server...

For those edge cases it would be nice to use firebase realtime as a backup source of truth, if some flag enabled wdyt?

**Comment by deathg0d** [comment]
Currently, it eventually syncs to Firestore, even if WebRTC fails. I'm not sure if adding Firebase Realtime Database is worth the added complexity. Theoretically, it could help with syncing **data** faster when WebRTC fails, but I wouldn't use it for **awareness updates** because they may be triggered far too frequently (probably will affect your costs).

**Comment by no-1ne** [comment]
you are right, going via DB for ephemeral data is inefficient, web sockets may be a better solution here.. instantdb can be a good fit..

https://www.instantdb.com/docs/presence-and-topics
